FROM python:3.12-slim

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv
COPY pyproject.toml uv.lock ./

RUN uv sync --frozen

COPY /src/ ./src/
COPY /migration/ ./migration/
COPY alembic.ini ./alembic.ini

RUN if [ ! -d "/app/migration" ]; then echo "migration folder not found!" && exit 1; fi
RUN if [ ! -f "/app/alembic.ini" ]; then echo "alembic.ini not found!" && exit 1; fi


CMD ["uv", "run", "alembic", "upgrade", "head"]