FROM python:3.14-slim-trixie

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-dev --no-install-project --no-editable

COPY src/ ./src/
COPY migration/ ./migration/
COPY alembic.ini ./

RUN test -d /app/migration && test -f /app/alembic.ini || \
    (echo "❌ Migration files missing!" && exit 1)

CMD ["uv", "run", "alembic", "upgrade", "head"]